apiVersion: apps/v1
kind: Deployment
metadata:
  name: mioke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mioke
  template:
    metadata:
      labels:
        app: mioke
    spec:
      containers:
      - image: okteto.dev/mioke:latest
        name: mioke
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "fdc0626d-6767-4229-b99a-bd5320032d3b"
        - name: Vless_Path
          value: "/kytfbsxwhrdxe"
        - name: Vmess_UUID
          value: "fdc0626d-6767-4229-b99a-bd5320032d3b"
        - name: Vmess_Path
          value: "/tfcesfrdwzkhotx"
        - name: Share_Path
          value: "/v2link"
