apiVersion: apps/v1
kind: Deployment
metadata:
  name: yert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yert
  template:
    metadata:
      labels:
        app: yert
    spec:
      containers:
      - image: okteto.dev/yert:latest
        name: yert
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "aea3422d-0a55-47d4-9310-5e6efe0677f1"
        - name: Vless_Path
          value: "/kyfcrvxwhrdxe"
        - name: Vmess_UUID
          value: "aea3422d-0a55-47d4-9310-5e6efe0677f1"
        - name: Vmess_Path
          value: "/mfcrsfrdwzkhotx"
        - name: Share_Path
          value: "/v2link"
